version: '3.8'
services:
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./dev_certs:/certs:ro
      - /app/node_modules
    command: sh -c 'npm ci --silent || true && npm run dev -- --host 0.0.0.0'
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev

  backend-dev:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./dev_certs:/certs:ro
      - /app/backend/.venv
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/npcchatter
      - FLASK_APP=backend.app:app
      - FLASK_ENV=development
      - FRONTEND_ORIGIN=https://lvh.me:5173
      - COOKIE_DOMAIN=.lvh.me
    command: sh -c "pip install --no-cache-dir -r /app/backend/requirements.txt || true && if [ -f /certs/dev.crt ] && [ -f /certs/dev.key ]; then flask run --host=0.0.0.0 --port=5001 --cert=/certs/dev.crt --key=/certs/dev.key; else flask run --host=0.0.0.0 --port=5001; fi"
    ports:
      - "5001:5001"
    depends_on:
      - db
