app = "npccv2-backend"

[build]
  # Build from the Dockerfile located in this directory (backend/Dockerfile).
  # When running `flyctl deploy --config backend/fly.toml` from the repo root,
  # Fly will use this config file and the build context below.
  dockerfile = "Dockerfile"
  context = "."

[env]
  PORT = "5001"

[[services]]
  internal_port = 5001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
