// This file is autogenerated by the assistant for debugging purposes.
// It contains a short git commit and a build timestamp so the UI can display
// a visible page version when ?debug=1 is passed in the URL.
export const APP_VERSION = '6b1ef73'
export const BUILD_TIME = '2025-08-25T15:30:48Z'
