name: Deploy Frontend to Vercel (manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: |
          npm install -g vercel@28

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Vercel Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Manual deploy using vercel CLI
          vercel deploy --prod --yes --token "$VERCEL_TOKEN"
