name: Deploy Backend to Fly

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          # Use the recommended way to add to PATH in GitHub Actions
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Login to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          $HOME/.fly/bin/flyctl auth token "$FLY_API_TOKEN"

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd backend
          $HOME/.fly/bin/flyctl deploy --config fly.toml --app npccv2-backend --remote-only
